### ISSUE TITLE
Any maintenance chances?

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-desktop-full#27]
Hi all,

Is there any chance, we could get updated versions of packages into AUR? They don't seem to be orphaned on AUR, but also not maintained, since all efforts seem to focus on noetic now?

Don't get me wrong, I absolutely understand the decision to restrict the amount of maintenance work, but melodic users (And some of us might be stuck with melodic at least for a couple of months) aren't able to leverage any AUR helper to manage their ROS installation anymore. 

Melodic is currently left with a non-consistent stage atm (e.g. the `controller_manager` doesn't match the `controller_manager_msgs` version) so it is not only a matter of being stuck with an old version.

I currently hold a bunch of updated packages locally on my system which doesn't feel ideal to me at all... Is there any chance I could get them synced to AUR?

**Comment by bionade24** [comment]
I'm working on it in the little time I have. The change of the folder structure has made it complicated for many packages, as those changes aren't predictable from the `distribution.yaml`.

**Comment by acxz** [comment]
@bionade24 Personally I would okay with adding @fmauch to the ros-melodic-arch org so that if he wants to he can update and commit new package versions. However, before that I would like to see @fmauch submit PRs to the packages so that we can trust his code quality before giving him write access. Similar to what I was doing before I joined the org.

Until we see this initiative on @fmauch's side with respect to PRs I wouldn't recommend him to join the org however. 
Also ultimately the syncing will be up to you, unless you add others to be co-maintainers on the packages.

Just my 2 cents

**Comment by bionade24** [comment]
The other issue resulting to the directory change seems to be a lot of linking issues, even I don't know why. Once I  found a good solution to get the new `_dir` paths,  the problem will be mostly gone. There aren't lots of bugs besides that one. I think @fmauch already contributed to some packages. I'll just need an idea to predict the new `_dir` vars.

**Comment by bionade24** [comment]
Just to maybe add it here: As I want to get the core packages working, I'll archive and disown not working things. `octomap`, a dep of moveit, still builds against qt4 in our package version, probably because there isn't `libqglviewer-qt5` available on Arch. If someone cares about the moveit stack, he should take the work on it, but I'll drop it when it doesn't build against the octo*-packages in my repo anymore.

**Comment by acxz** [comment]
Instead of disowning the packages can you instead hand them over to someone that has access to the repos in this organization (like me :)).
I think that would be better to keep the ros-melodic packages together even if they are not being maintained by you. I would hate to have another party get the packages and then branch off development from these repos. We are already small as is. I would only disown a package if you can hand it off to someone in the community that we trust and know can take care of them.

Even if I won't actively maintain them, I would still be wiling to sync the packages from this repo to the AUR.

> @fmauch already contributed
If thats the case, then let's add him asap!!

**Comment by acxz** [comment]
Actually don't hand them over to me lol, I'm already busy as it maintaining noetic, don't want to pick up responsibility of syncing some melodic packages when I might not be able to do even that.

But once @fmauch joins the org, I would nominate you hand the packages over to him or keep them honestly. Just to ensure that repo development and AUR packages can stay in the same development vein and no work ends up getting duplicated.

This is just my opinion/suggestion don't take it too heavily. I'm never gonna use melodic again anyway so my opinion shouldn't matter much.

**Comment by bionade24** [comment]
Ok, I reverted the things and opened an issue at `ros-melodic-octovis` instead for moving to Qt5. Seem like I found a solution to get the names. But before we do it, @fmauch Do you want to contribute more often and  help maintaining the packages?

**Comment by fmauch** [comment]
I'd be happy to make those PRs as I still maintain a couple of packages locally for my machine. I just didn't do the PRs as I wasn't sure whether it was worth the effort.

**Comment by bionade24** [comment]
Are the PR's  still open or just not synced?

**Comment by fmauch** [comment]
I also use moveit (at least as a dependency) in my daily work so I would also try to rectify that.

**Comment by bionade24** [comment]
Ok, then we'll go for it. Just give me a day to fix the path issues in all the packges and hopefully then most things will built, otherwise I'll open issues. Would be nice if you could take care of `ros-melodic-octovis` package. I'm not working with moveit anymore, so I don't have a focus on it and its deps.

**Comment by fmauch** [comment]
In fact, octovis isn't a dependency of the moveit stack, so it isn't really blocking anything as far as I understand. But I'll have a look at it.

**Comment by acxz** [comment]
@fmauch we just want to ensure that the AUR packages are in line with the repos here, which is why we want ros-melodic-* AUR packages to be maintained by at least someone part of this org. 

If you or @bionade24 really don't want to maintain it, just add me as a co-maintainer to the AUR package before you disown it so that the maintainership of it will be transferred to me.

**Comment by fmauch** [comment]
How does the syncing process actually work currently?

I'm asking mainly for new packages. E.g. for [`ros-melodic-joint-trajectory-controller](https://github.com/ros-melodic-arch/ros-melodic-joint-trajectory-controller) I have an open PR since a while. Should I create the AUR package and sync it manually? Or would you two @acxz  and @bionade24 like to keep ownership of the AUR packages and take care of the syncing. I would be fine with both, but I guess the first solution is more useful as I will be maintaining those packages, anyway.

**Comment by acxz** [comment]
> How does the syncing process actually work currently?

Currently and for some months now @bionade24 has been handling it. I assume @bionade24 clones the latest version of the repos and then attempts to build them in a clean chroot. If the package is successfully the resulting package `.tar.xz` file gets uploaded to @bionade24's personal binary repository (oscloud) and the PKGBUILD to the AUR. This is a bit problematic in the sense that the PKGBUILD does not get synced if the build is unsuccessful. So if you want to build / debug the packages en mass using an AUR helper tool it is quite difficult.

For ros-noetic-* I do not use a personal binary repo, but if it works on my system I'll make the commit/merge the PR and sync to the AUR immediately when the commit/merge is applied. For binary packages progress is under way with the help of [arch4edu](https://github.com/arch4edu/arch4edu/issues/78).

> I'm mainly asking for new packages.

When I needed to create new ros-melodic packages. I would do the following to get around @bionade24's syncing process. I would create the repo in this org and then sync it manually (by adding the AUR ssh link as another git remote and pushing to it). After it being up on the AUR I would give @bionade24 co-maintainership and then disown it. This process takes some load off of @bionade24 in that the repo and the package are created and the package is now easily part of the process that @bionade24's uses to sync.

> I will be maintaining those packages

I would make you a member of this org rn if I could, but I'm afraid only @bionade24 has permissions for that. We will have to wait on him.

> Should I create the AUR package and sync it manually?

Up to you, if I were you I would just wait for a day. @bionade24's prob sleeping now ;)
I personally do not spend anytime on melodic anymore, so I would be the last person to hand it over to. (In fact, I'm pushing for people to get on noetic ASAP so that our the Arch Robotics community doesn't get splintered as much. ;))

**Comment by acxz** [comment]
Oh wait you a memba now, congraz!

I would follow these suggestions for new packages:

> When I needed to create new ros-melodic packages. I would do the following to get around @bionade24's syncing process. I would create the repo in this org and then sync it manually (by adding the AUR ssh link as another git remote and pushing to it). After it being up on the AUR I would give @bionade24 co-maintainership and then disown it. This process takes some load off of @bionade24 in that the repo and the package are created and the package is now easily part of the process that @bionade24's uses to sync.

Any packages that @bionade24 doesn't want to sync/maintain you can just keep maintain them yourself as long as their is an appropriate mirror repo in this org for it.

**Comment by acxz** [comment]
I think we can close this issue and for any specific packages not synced. Open an issue on that respective repo's github with the `sync to AUR` label, so that @bionade24 knows which ones to prioritize.

See previous issues with that label for examples. Here is one: https://github.com/ros-melodic-arch/ros-melodic-mavros/issues/1

**Comment by bionade24** [comment]
@fmauch I have a script to update the PKGBUILDs: https://github.com/bionade24/ros-aur-helpers 
Calling `ci.py update <pkg_name>` will update the package, first time you should call `ci.py clone all` to download the PKGBUILD files.
The biggest problem I currently have are the new folder structures. I tried to enhance it with [this commit](https://github.com/bionade24/ros-aur-helpers/commit/6a76ed6443c71e2748292a6c39b594a38044d437), but it that doesn't work for `ompl`,  bc they use a different new structure than `ros` or `ros_comm`. @acxz Maybe you have an idea, too?

**Comment by acxz** [comment]
I am afraid I do not have an idea.

Also for your script/repo you should put it in the https://github.com/ros-arch organization.
